//==================================================
//     Outputs that match the input variables
//==================================================
output "unix_interpreter" {
  description = "The value of the `unix_interpreter` input variable, or the default value if the input was `null`."
  value       = local.var_unix_interpreter
}

//==================================================
//       Outputs generated by this module
//==================================================
output "uuid" {
  description = "The generated UUID."
  value       = local.uuid
}
